### ISSUE TITLE
Consider adding it to the AUR

### ISSUE THREAD

**Issue by memeplex** [loopzen/pomobar#1]
I guess this is most useful for people in arch (even manjaro) which tend to go DIY and use polybar, so why not adding a PKGBUILD the the AUR?

**Comment by mxmilkb** [comment]
Anyone can add an AUR package, so I did so :)

https://aur.archlinux.org/packages/pomobar

A rush job, missing dependencies, will sort that in time when someone complains here or there.

**Comment by loopzen** [comment]
Thank you. I didn't know if someone would use it.
